name: Build ZMK firmware
# Can also be run manually from the Actions tab (workflow_dispatch).
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
